/// A single food/venue category
///
/// [id] is the API value sent in requests. [label] is the text shown on the corresponding
/// FilterButton.
class FoodCategory {
  const FoodCategory({required this.id, required this.label});

  final String id;
  final String label;
}

/// The collection of all food types that are not in [popular].
///
/// These categories are sourced from Table A of Google's Place Types:
/// https://developers.google.com/maps/documentation/places/web-service/place-types#table-a
const List<FoodCategory> all = [
  FoodCategory(id: 'acai_shop', label: 'Acai Shop'),
  FoodCategory(id: 'afghani_restaurant', label: 'Afghani'),
  FoodCategory(id: 'african_restaurant', label: 'African'),
  FoodCategory(id: 'american_restaurant', label: 'American'),
  FoodCategory(id: 'argentinian_restaurant', label: 'Argentinian'),
  FoodCategory(id: 'asian_fusion_restaurant', label: 'Asian Fusion'),
  FoodCategory(id: 'asian_restaurant', label: 'Asian'),
  FoodCategory(id: 'australian_restaurant', label: 'Australian'),
  FoodCategory(id: 'austrian_restaurant', label: 'Austrian'),
  FoodCategory(id: 'bagel_shop', label: 'Bagel Shop'),
  FoodCategory(id: 'bakery', label: 'Bakery'),
  FoodCategory(id: 'bangladeshi_restaurant', label: 'Bangladeshi'),
  FoodCategory(id: 'bar', label: 'Bar'),
  FoodCategory(id: 'bar_and_grill', label: 'Bar and Grill'),
  FoodCategory(id: 'basque_restaurant', label: 'Basque'),
  FoodCategory(id: 'bavarian_restaurant', label: 'Bavarian'),
  FoodCategory(id: 'beer_garden', label: 'Beer Garden'),
  FoodCategory(id: 'belgian_restaurant', label: 'Belgian'),
  FoodCategory(id: 'bistro', label: 'Bistro'),
  FoodCategory(id: 'brazilian_restaurant', label: 'Brazilian'),
  FoodCategory(id: 'brewery', label: 'Brewery'),
  FoodCategory(id: 'brewpub', label: 'Brewpub'),
  FoodCategory(id: 'british_restaurant', label: 'British'),
  FoodCategory(id: 'brunch_restaurant', label: 'Brunch'),
  FoodCategory(id: 'buffet_restaurant', label: 'Buffet'),
  FoodCategory(id: 'burmese_restaurant', label: 'Burmese'),
  FoodCategory(id: 'burrito_restaurant', label: 'Burrito'),
  FoodCategory(id: 'cajun_restaurant', label: 'Cajun'),
  FoodCategory(id: 'cake_shop', label: 'Cake Shop'),
  FoodCategory(id: 'californian_restaurant', label: 'Californian'),
  FoodCategory(id: 'cambodian_restaurant', label: 'Cambodian'),
  FoodCategory(id: 'candy_store', label: 'Candy Store'),
  FoodCategory(id: 'cantonese_restaurant', label: 'Cantonese'),
  FoodCategory(id: 'caribbean_restaurant', label: 'Caribbean'),
  FoodCategory(id: 'cat_cafe', label: 'Cat Cafe'),
  FoodCategory(id: 'chicken_restaurant', label: 'Chicken'),
  FoodCategory(id: 'chicken_wings_restaurant', label: 'Chicken Wings'),
  FoodCategory(id: 'chilean_restaurant', label: 'Chilean'),
  FoodCategory(id: 'chinese_noodle_restaurant', label: 'Chinese Noodle'),
  FoodCategory(id: 'chocolate_factory', label: 'Chocolate Factory'),
  FoodCategory(id: 'chocolate_shop', label: 'Chocolate Shop'),
  FoodCategory(id: 'cocktail_bar', label: 'Cocktail Bar'),
  FoodCategory(id: 'coffee_roastery', label: 'Coffee Roastery'),
  FoodCategory(id: 'coffee_shop', label: 'Coffee Shop'),
  FoodCategory(id: 'coffee_stand', label: 'Coffee Stand'),
  FoodCategory(id: 'colombian_restaurant', label: 'Colombian'),
  FoodCategory(id: 'confectionery', label: 'Confectionery'),
  FoodCategory(id: 'croatian_restaurant', label: 'Croatian'),
  FoodCategory(id: 'cuban_restaurant', label: 'Cuban'),
  FoodCategory(id: 'czech_restaurant', label: 'Czech'),
  FoodCategory(id: 'danish_restaurant', label: 'Danish'),
  FoodCategory(id: 'deli', label: 'Deli'),
  FoodCategory(id: 'dessert_restaurant', label: 'Dessert'),
  FoodCategory(id: 'dessert_shop', label: 'Dessert Shop'),
  FoodCategory(id: 'dim_sum_restaurant', label: 'Dim Sum'),
  FoodCategory(id: 'diner', label: 'Diner'),
  FoodCategory(id: 'dog_cafe', label: 'Dog Cafe'),
  FoodCategory(id: 'donut_shop', label: 'Donut Shop'),
  FoodCategory(id: 'dumpling_restaurant', label: 'Dumpling'),
  FoodCategory(id: 'dutch_restaurant', label: 'Dutch'),
  FoodCategory(id: 'eastern_european_restaurant', label: 'Eastern European'),
  FoodCategory(id: 'ethiopian_restaurant', label: 'Ethiopian'),
  FoodCategory(id: 'european_restaurant', label: 'European'),
  FoodCategory(id: 'falafel_restaurant', label: 'Falafel'),
  FoodCategory(id: 'family_restaurant', label: 'Family'),
  FoodCategory(id: 'fast_food_restaurant', label: 'Fast Food'),
  FoodCategory(id: 'filipino_restaurant', label: 'Filipino'),
  FoodCategory(id: 'fish_and_chips_restaurant', label: 'Fish and Chips'),
  FoodCategory(id: 'fondue_restaurant', label: 'Fondue'),
  FoodCategory(id: 'french_restaurant', label: 'French'),
  FoodCategory(id: 'fusion_restaurant', label: 'Fusion'),
  FoodCategory(id: 'gastropub', label: 'Gastropub'),
  FoodCategory(id: 'german_restaurant', label: 'German'),
  FoodCategory(id: 'greek_restaurant', label: 'Greek'),
  FoodCategory(id: 'gyro_restaurant', label: 'Gyro'),
  FoodCategory(id: 'halal_restaurant', label: 'Halal'),
  FoodCategory(id: 'hamburger_restaurant', label: 'Hamburger'),
  FoodCategory(id: 'hawaiian_restaurant', label: 'Hawaiian'),
  FoodCategory(id: 'hot_dog_stand', label: 'Hot Dog Stand'),
  FoodCategory(id: 'hot_pot_restaurant', label: 'Hot Pot'),
  FoodCategory(id: 'hungarian_restaurant', label: 'Hungarian'),
  FoodCategory(id: 'ice_cream_shop', label: 'Ice Cream Shop'),
  FoodCategory(id: 'indonesian_restaurant', label: 'Indonesian'),
  FoodCategory(id: 'irish_pub', label: 'Irish Pub'),
  FoodCategory(id: 'irish_restaurant', label: 'Irish'),
  FoodCategory(id: 'japanese_curry_restaurant', label: 'Japanese Curry'),
  FoodCategory(id: 'japanese_izakaya_restaurant', label: 'Japanese Izakaya'),
  FoodCategory(id: 'juice_shop', label: 'Juice Shop'),
  FoodCategory(id: 'kebab_shop', label: 'Kebab Shop'),

  FoodCategory(id: 'korean_restaurant', label: 'Korean'),
  FoodCategory(id: 'latin_american_restaurant', label: 'Latin American'),
  FoodCategory(id: 'lebanese_restaurant', label: 'Lebanese'),
  FoodCategory(id: 'lounge_bar', label: 'Lounge Bar'),
  FoodCategory(id: 'malaysian_restaurant', label: 'Malaysian'),
  FoodCategory(id: 'mediterranean_restaurant', label: 'Mediterranean'),
  FoodCategory(id: 'middle_eastern_restaurant', label: 'Middle Eastern'),
  FoodCategory(
    id: 'mongolian_barbecue_restaurant',
    label: 'Mongolian Barbecue',
  ),
  FoodCategory(id: 'moroccan_restaurant', label: 'Moroccan'),
  FoodCategory(id: 'noodle_shop', label: 'Noodle Shop'),
  FoodCategory(id: 'north_indian_restaurant', label: 'North Indian'),
  FoodCategory(id: 'oyster_bar_restaurant', label: 'Oyster Bar'),
  FoodCategory(id: 'pakistani_restaurant', label: 'Pakistani'),
  FoodCategory(id: 'pastry_shop', label: 'Pastry Shop'),
  FoodCategory(id: 'persian_restaurant', label: 'Persian'),
  FoodCategory(id: 'peruvian_restaurant', label: 'Peruvian'),
  FoodCategory(id: 'polish_restaurant', label: 'Polish'),
  FoodCategory(id: 'portuguese_restaurant', label: 'Portuguese'),
  FoodCategory(id: 'pub', label: 'Pub'),
  FoodCategory(id: 'ramen_restaurant', label: 'Ramen'),
  FoodCategory(id: 'romanian_restaurant', label: 'Romanian'),
  FoodCategory(id: 'russian_restaurant', label: 'Russian'),
  FoodCategory(id: 'salad_shop', label: 'Salad Shop'),
  FoodCategory(id: 'sandwich_shop', label: 'Sandwich Shop'),
  FoodCategory(id: 'scandinavian_restaurant', label: 'Scandinavian'),
  FoodCategory(id: 'shawarma_restaurant', label: 'Shawarma'),
  FoodCategory(id: 'snack_bar', label: 'Snack Bar'),
  FoodCategory(id: 'soul_food_restaurant', label: 'Soul Food'),
  FoodCategory(id: 'soup_restaurant', label: 'Soup'),
  FoodCategory(id: 'south_american_restaurant', label: 'South American'),
  FoodCategory(id: 'south_indian_restaurant', label: 'South Indian'),
  FoodCategory(id: 'southwestern_us_restaurant', label: 'Southwestern US'),
  FoodCategory(id: 'spanish_restaurant', label: 'Spanish'),
  FoodCategory(id: 'sports_bar', label: 'Sports Bar'),
  FoodCategory(id: 'sri_lankan_restaurant', label: 'Sri Lankan'),
  FoodCategory(id: 'steak_house', label: 'Steak House'),
  FoodCategory(id: 'swiss_restaurant', label: 'Swiss'),
  FoodCategory(id: 'taco_restaurant', label: 'Taco'),
  FoodCategory(id: 'taiwanese_restaurant', label: 'Taiwanese'),
  FoodCategory(id: 'tapas_restaurant', label: 'Tapas'),
  FoodCategory(id: 'tea_house', label: 'Tea House'),
  FoodCategory(id: 'tex_mex_restaurant', label: 'Tex Mex'),
  FoodCategory(id: 'tibetan_restaurant', label: 'Tibetan'),
  FoodCategory(id: 'tonkatsu_restaurant', label: 'Tonkatsu'),
  FoodCategory(id: 'turkish_restaurant', label: 'Turkish'),
  FoodCategory(id: 'ukrainian_restaurant', label: 'Ukrainian'),
  FoodCategory(id: 'vegan_restaurant', label: 'Vegan'),
  FoodCategory(id: 'vegetarian_restaurant', label: 'Vegetarian'),
  FoodCategory(id: 'vietnamese_restaurant', label: 'Vietnamese'),
  FoodCategory(id: 'western_restaurant', label: 'Western'),
  FoodCategory(id: 'wine_bar', label: 'Wine Bar'),
  FoodCategory(id: 'winery', label: 'Winery'),
  FoodCategory(id: 'yakiniku_restaurant', label: 'Yakiniku'),
  FoodCategory(id: 'yakitori_restaurant', label: 'Yakitori'),
];

/// A collection of popular cuisines.
/// 
/// These exist separately to give them priority when populating the
/// search filters buttons on the main screen.
const List<FoodCategory> popular = [
  FoodCategory(id: 'pizza_restaurant', label: 'Pizza'),
  FoodCategory(id: 'chinese_restaurant', label: 'Chinese'),
  FoodCategory(id: 'japanese_restaurant', label: 'Japanese'),

  FoodCategory(id: 'mexican_restaurant', label: 'Mexican'),
  FoodCategory(id: 'sushi_restaurant', label: 'Sushi'),
  FoodCategory(id: 'italian_restaurant', label: 'Italian'),

  FoodCategory(id: 'korean_barbecue_restaurant', label: 'Korean Barbecue'),
  FoodCategory(id: 'thai_restaurant', label: 'Thai'),
  FoodCategory(id: 'indian_restaurant', label: 'Indian'),
  FoodCategory(id: 'seafood_restaurant', label: 'Seafood'),
  FoodCategory(id: 'cafe', label: 'Cafe'),
  FoodCategory(id: 'breakfast_restaurant', label: 'Breakfast'),
  FoodCategory(id: 'barbecue_restaurant', label: 'Barbecue'),
];
